{% set name = "stylist" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f48ac66f1f8a3d884f3fd923fbae92a5855e2bc7b858131a5788de73f195005

build:
  entry_points:
    - stylist=stylist.__main__:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fparser >=0.1.2
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - stylist
  commands:
    - stylist --help

about:
  home: https://github.com/MetOffice/stylist
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible code style checker
  description: |
    Extensible code style checker currently supporting Fortran, PSyclone DSL, etc
  doc_url: https://github.com/MetOffice/stylist
  dev_url: https://github.com/MetOffice/stylist

extra:
  recipe-maintainers:
    - matthewrmshin
    - MatthewHambley
    - allynt
    - mo-lucy-gordon

