{% set name = "stylist" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14d1a63806336499ff087e9b8263f29d60a077ab9f4b9cd14c211286e581152c

build:
  entry_points:
    - stylist=stylist.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fparser
    - python >=3.6

test:
  imports:
    - stylist
  commands:
    - stylist --help

about:
  home: https://github.com/MetOffice/stylist
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible code style checker
  description: |
    Extensible code style checker currently supporting Fortran, PSyclone DSL, etc
  doc_url: https://github.com/MetOffice/stylist
  dev_url: https://github.com/MetOffice/stylist

extra:
  recipe-maintainers:
    - matthewrmshin
    - MatthewHambley
